Repository AY2021S2-CS2103T-T11-2/tp, pull requests merged in 2021-04, with the labels that each got.

#267 Remove unnecessary listener
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddGroupmateCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupmateCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateContactCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateGroupmateCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewProjectCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/test/java/seedu/address/logic/commands/DeleteProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddGroupmateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTodoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupmateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTodoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateContactCommandParserTest.java
Labels: type.Bug

#251 Update UG with advice from CS2101 consultation
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpPanel.java
Labels: priority.Medium, type.Documentation, type.Enhancement

#272 Fix description message constraints & update help panel
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/ui/HelpPanel.java
Labels: priority.Medium, type.Bug

#270 Updates to UG
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/images/Ui.png
  docs/images/app_window_sections.png
  docs/images/contacts.png
  docs/images/deadlines.png
  docs/images/events.png
  docs/images/groupmates.png
  docs/images/project.png
  docs/images/today.png
  docs/images/todos.png
  src/main/java/seedu/address/ui/HelpPanel.java
Labels: type.Documentation

#276 UG: Update command format info
  docs/UserGuide.md
Labels: priority.Medium, type.Bug, type.Documentation

#278 UG: Fix formatting
  docs/UserGuide.md
Labels: priority.Medium, type.Bug, type.Documentation

#281 Merge branch 'master' into branch-bug-fix
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/ui/HelpPanel.java
Labels: priority.High, type.Bug, type.Documentation, type.Story

#283 Bunch of bug fixes
  docs/UserGuide.md
Labels: priority.High, type.Bug, type.Documentation, type.Story

#340 Update PPP - Vevek
  docs/team/vevek.md
Labels: type.Documentation

#341 update PPP
  docs/team/eriksen2411.md
Labels: priority.Medium, type.Documentation

#346 Fix contact tag and groupmate role validation, update relevant parts of UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/groupmate/Role.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/groupmate/RoleTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Bug, type.Documentation

#349 Bunch of bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/MarkTodoCommand.java
  src/main/java/seedu/address/logic/commands/UpdateContactCommand.java
  src/main/java/seedu/address/logic/commands/UpdateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/logic/commands/UpdateGroupmateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateProjectCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTodoCommand.java
  src/main/java/seedu/address/storage/JsonSerializableColabFolder.java
  src/main/resources/view/ContactListPanel.fxml
  src/test/java/seedu/address/logic/commands/UpdateContactCommandTest.java
Labels: priority.High, type.Bug, type.Documentation

#350 Update DG and remove trailing space in md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
  docs/team/samuelfangjw.md
  docs/team/vevek.md
Labels: priority.High, type.Documentation

#344 Update Use Cases
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#361 Update PPP - Vevek
  docs/team/vevek.md
Labels: type.Documentation

#354 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTodoParserSequenceDiagram.puml
  docs/diagrams/DeleteTodoSequenceDiagram.puml
  docs/diagrams/ProjectClassDiagram.puml
  docs/images/DeleteTodoParserSequenceDiagram.png
  docs/images/DeleteTodoSequenceDiagram.png
  docs/images/ProjectClassDiagram.png
  src/main/java/seedu/address/model/task/Interval.java
Labels: priority.High, type.Documentation

#360 Unit testing for updateP, updateE, updateD, updateT command
  src/main/java/seedu/address/logic/commands/UpdateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/logic/commands/UpdateProjectCommand.java
  src/main/java/seedu/address/logic/parser/UpdateProjectCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateContactCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateDeadlineDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UpdateEventCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateEventDescriptorTest.java
  src/test/java/seedu/address/logic/commands/UpdateProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTodoCommandTest.java
  src/test/java/seedu/address/logic/parser/ColabParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateProjectCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateTodoCommandParserTest.java
Labels: severity.Medium, type.Task

#362 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#363 Update DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#366 Update update commands implementation
  docs/DeveloperGuide.md
  docs/diagrams/UpdateGroupmateCommandSequenceDiagram.puml
  docs/diagrams/UpdateProjectCommandSequenceDiagram.puml
  docs/images/UpdateGroupmateCommandSequenceDiagram.png
  docs/images/UpdateProjectCommandSequenceDiagram.png
Labels: type.Documentation

#364 Update DG with diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddEventCommandSequenceDiagram.puml
  docs/images/AddEventCommandSequenceDiagram.png
Labels: priority.High, type.Documentation

#371 Format doc
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/Testing.md
  docs/UserGuide.md
Labels: type.Documentation

#370 Add page breaks to documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#373 Wrap lines for long sequence diagrams and fix capitalization
  docs/DeveloperGuide.md
  docs/diagrams/UpdateGroupmateCommandSequenceDiagram.puml
  docs/diagrams/UpdateProjectCommandSequenceDiagram.puml
  docs/images/UpdateGroupmateCommandSequenceDiagram.png
  docs/images/UpdateProjectCommandSequenceDiagram.png
Labels: type.Documentation

#375 Minor changes to DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ViewProjectCommandSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ViewProjectCommandSequenceDiagram.png
Labels: type.Documentation

#374 minor changes to ug
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation, type.Enhancement

#376 Bug fixes
  docs/team/vevek.md
  src/main/java/seedu/address/commons/util/TimeUtil.java
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTodoCommand.java
  src/main/java/seedu/address/logic/parser/DeleteDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTodoCommandParser.java
  src/main/java/seedu/address/model/task/deadline/Deadline.java
  src/main/java/seedu/address/model/task/todo/Todo.java
Labels: priority.High, type.Documentation, type.Task

#378 Update reposense link
  docs/team/lirc572.md
Labels: priority.High, type.Documentation

#377 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteTodoParserSequenceDiagram.puml
  docs/images/DeleteTodoParserSequenceDiagram.png
Labels: type.Documentation

#381 Updated code for some tests. Will not affect main app.
  src/test/java/seedu/address/logic/commands/AddDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTodoCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTodoCommandTest.java
  src/test/java/seedu/address/model/task/deadline/DeadlineTest.java
  src/test/java/seedu/address/model/task/repeatable/EventTest.java
  src/test/java/seedu/address/model/task/todo/TodoTest.java
Labels: type.Task

#380 update Danh's PPP
  docs/team/eriksen2411.md
  docs/team/vevek.md
Labels: priority.High, type.Documentation

#387 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#388 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#389 Update PPP
  docs/team/vevek.md
Labels: type.Documentation

#390 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#391 Update UG
  docs/UserGuide.md
  docs/images/app_window_section_contacts.png
  docs/images/app_window_section_help.png
  docs/images/app_window_section_main.png
  docs/images/app_window_section_overview.png
  docs/images/app_window_section_today.png
  docs/images/app_window_section_todos.png
  docs/images/app_window_sections.png
Labels: type.Documentation

#392 Update UG
  docs/UserGuide.md
  docs/images/app_window_section_projects.png
  docs/images/ug_section_contact.png
  docs/images/ug_section_deadline.png
  docs/images/ug_section_event.png
  docs/images/ug_section_findc.png
  docs/images/ug_section_groupmate.png
  docs/images/ug_section_today.png
  docs/images/ug_section_todo.png
Labels: type.Documentation
