Repository AY2021S2-CS2103T-T11-2/tp, pull requests merged in 2021-02, with the labels that each got.

#14 Update config file
  docs/_config.yml
Labels: type.Task

#18 Update User Guide for v1.1
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High, type.Documentation

#9 Update user guide on details of view command
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#19 Update README for v1.1
  README.md
Labels: priority.High, type.Documentation

#21 Update product summary phrasing in User Guide for v1.1
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#31 Update [Coming Soon] in User Guide for v1.1
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#28 Update Project Site
  docs/UserGuide.md
  docs/index.md
Labels: type.Documentation

#30 Update acknowledgments in README file
  README.md
Labels: type.Documentation

#29 Update about us page
  docs/AboutUs.md
  docs/images/eriksen2411.png
  docs/images/lirc572.png
  docs/images/samuelfangjw.png
  docs/images/vevek.png
  docs/team/eriksen2411.md
  docs/team/lirc572.md
  docs/team/samuelfangjw.md
  docs/team/vevek.md
Labels: priority.High, type.Documentation

#10 Update Developer guide for v1.1
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#26 Update NFR in developer guide for v1.1
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#33 Fix broken links
  README.md
  docs/index.md
Labels: severity.Medium, type.Bug, type.Documentation

#46 Add logo to README and index page of site
  README.md
  docs/images/logo.png
  docs/index.md
Labels: type.Documentation

#48 Update site links in sitemap of README.md
  README.md
Labels: type.Documentation

#56 Remove whitespace in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation, type.Task
