Repository AY2021S2-CS2103T-T11-2/tp, pull requests merged in 2021-03, with the labels that each got.

#59 Fix developer guide toc
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#67 Update user guide link in help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#66 Add Task & related models
  src/main/java/seedu/address/commons/exceptions/DateConversionException.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/model/task/Completable.java
  src/main/java/seedu/address/model/task/Interval.java
  src/main/java/seedu/address/model/task/Repeatable.java
  src/main/java/seedu/address/model/task/completable/Deadline.java
  src/main/java/seedu/address/model/task/completable/Todo.java
  src/main/java/seedu/address/model/task/repeatable/Event.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/model/task/completable/DeadlineTest.java
  src/test/java/seedu/address/model/task/completable/TodoTest.java
  src/test/java/seedu/address/model/task/repeatable/EventTest.java
Labels: priority.High, type.Task

#70 Add-project command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ProjectsFolder.java
  src/main/java/seedu/address/model/ReadOnlyProjectsFolder.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/project/CompletableTaskList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/ParticipantList.java
  src/main/java/seedu/address/model/task/Completable.java
  src/main/java/seedu/address/model/task/completable/Deadline.java
  src/main/java/seedu/address/model/task/completable/Todo.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompletable.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonProjectsFolderStorage.java
  src/main/java/seedu/address/storage/JsonSerializableProjectsFolder.java
  src/main/java/seedu/address/storage/ProjectsFolderStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Story

#83 Modular UI commands
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiCommand.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Task

#86 Remove unused assertion from DateUtil
  src/main/java/seedu/address/commons/util/DateUtil.java
Labels: priority.High, type.Story, type.Task

#90 Add listC and listP commands
  src/main/java/seedu/address/logic/commands/ListContactsCommand.java
  src/main/java/seedu/address/logic/commands/ListProjectsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiCommand.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListContactsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListProjectsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.Medium, type.Story

#88 Update Deadline, Todo and relevant models as separate entities
  src/main/java/seedu/address/model/project/CompletableTaskList.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/TodoList.java
  src/main/java/seedu/address/model/task/CompletableDeadline.java
  src/main/java/seedu/address/model/task/CompletableTodo.java
  src/main/java/seedu/address/model/task/deadline/Deadline.java
  src/main/java/seedu/address/model/task/todo/Todo.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonAdaptedTodo.java
  src/test/java/seedu/address/model/project/CompletableTaskListTest.java
  src/test/java/seedu/address/model/project/DeadlineListTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/project/TodoListTest.java
  src/test/java/seedu/address/model/task/deadline/DeadlineTest.java
  src/test/java/seedu/address/model/task/repeatable/EventTest.java
  src/test/java/seedu/address/model/task/todo/TodoTest.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.High, type.Enhancement, type.Story, type.Task

#80 AddEto command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/repeatable/Event.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
Labels: priority.High, type.Story

#104 deleteP command implementation
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteProjectCommandParser.java
Labels: priority.High, type.Story

#102 Add AddDeadline feature and related functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/Project.java
Labels: priority.High, type.Story, type.Task

#93 Add tests utility
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/ParticipantList.java
  src/main/java/seedu/address/model/project/TodoList.java
  src/main/java/seedu/address/model/task/repeatable/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/java/seedu/address/model/ProjectsFolderTest.java
  src/test/java/seedu/address/model/project/DeadlineListTest.java
  src/test/java/seedu/address/model/project/EventListTest.java
  src/test/java/seedu/address/model/project/ParticipantListTest.java
  src/test/java/seedu/address/model/project/TodoListTest.java
  src/test/java/seedu/address/model/task/deadline/DeadlineTest.java
  src/test/java/seedu/address/model/task/repeatable/EventTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTodoTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/DeadlineBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/ProjectsFolderBuilder.java
  src/test/java/seedu/address/testutil/TodoBuilder.java
Labels: priority.Medium

#98 Add deleteT command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTodoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteProjectCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTodoCommandParser.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/TodoList.java
Labels: priority.High, type.Story, type.Task

#82 Implement addCto command
  src/main/java/seedu/address/logic/commands/AddContactToCommand.java
  src/main/java/seedu/address/logic/parser/AddContactToCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/project/ParticipantList.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/logic/commands/AddContactToCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListProjectsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactToCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story

#61 Implement GUI testing using TestFX
  .github/workflows/gradle.yml
  README.md
  build.gradle
  docs/index.md
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/GuiUnitTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/seedu/address/ui/testutil/StageExtension.java
  src/test/java/seedu/address/ui/testutil/UiPartExtension.java
Labels: type.Task

#99 Add deleteE command
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
Labels: priority.High, type.Story, type.Task

#109 Add tests
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/test/data/JsonProjectsFolderStorageTest/invalidAndValidProjectProjectsFolder.json
  src/test/data/JsonProjectsFolderStorageTest/invalidProjectProjectsFolder.json
  src/test/data/JsonProjectsFolderStorageTest/notJsonFormatProjectsFolder.json
  src/test/data/JsonSerializableProjectsFolderTest/duplicateProjectProjectsFolder.json
  src/test/data/JsonSerializableProjectsFolderTest/invalidProjectProjectsFolder.json
  src/test/data/JsonSerializableProjectsFolderTest/typicalProjectsProjectsFolder.json
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ProjectsFolderTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/project/UniqueProjectListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonProjectsFolderStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableProjectsFolderTest.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: type.Task

#114 Add mark Deadline as done feature
  src/main/java/seedu/address/logic/commands/MarkDeadlineCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkDeadlineCommandParser.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/TodoList.java
Labels: priority.High, type.Story, type.Task

#115 Add mark Event as done feature
  src/main/java/seedu/address/logic/commands/MarkEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkEventCommandParser.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
Labels: priority.High, type.Story, type.Task

#108 Add DeleteContactFromCommand and its parser
  .gitignore
  .vscode/extensions.json
  src/main/java/seedu/address/logic/commands/DeleteContactFromCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteContactFromCommandParser.java
  src/main/java/seedu/address/model/project/ParticipantList.java
  src/main/java/seedu/address/model/project/Project.java
  src/test/java/seedu/address/logic/commands/DeleteContactFromCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteContactFromCommandParserTest.java
  src/test/java/seedu/address/model/project/ParticipantListTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
Labels: priority.High

#119 Adds and updates tests for classes related to deleteProject command.
  src/test/java/seedu/address/logic/commands/DeleteProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteProjectCommandParserTest.java
Labels: priority.High, type.Story, type.Task

#123 Update sample projects with more realistic samples
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableProjectsFolderTest/typicalProjectsProjectsFolder.json
  src/test/java/seedu/address/logic/commands/AddContactToCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactFromCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/ListProjectsCommandTest.java
  src/test/java/seedu/address/model/ProjectsFolderTest.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: priority.Low

#121 UI redesign
  src/main/java/seedu/address/logic/commands/ListProjectsCommand.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/TodoList.java
  src/main/java/seedu/address/ui/CompletableDeadlineCard.java
  src/main/java/seedu/address/ui/CompletableTodoCard.java
  src/main/java/seedu/address/ui/HomePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/java/seedu/address/ui/SidePanel.java
  src/main/java/seedu/address/ui/UiCommand.java
  src/main/resources/view/CompletableDeadlineListCard.fxml
  src/main/resources/view/CompletableTodoListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HomePanel.css
  src/main/resources/view/HomePanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ProjectDisplayPanel.css
  src/main/resources/view/ProjectDisplayPanel.fxml
  src/main/resources/view/ProjectListCard.fxml
  src/main/resources/view/SidePanel.css
  src/main/resources/view/SidePanel.fxml
  src/test/java/seedu/address/logic/commands/ListProjectsCommandTest.java
Labels: priority.Low

#120 Updated classes, added tests for addEto command
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Story, type.Task

#127 Fix delete bug
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/TodoList.java
Labels: priority.High, severity.High, type.Bug

#129 Add tests for Add Todo command & it's related tests
  src/main/java/seedu/address/logic/commands/AddDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/logic/parser/AddTodoCommandParser.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTodoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTodoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TodoBuilder.java
Labels: priority.High, type.Story, type.Task

#134 Add tests for Add Deadline command & it's related tests
  src/main/java/seedu/address/logic/parser/AddDeadlineCommandParser.java
  src/test/java/seedu/address/logic/commands/AddDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Story, type.Task

#126 Update documentation
  README.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/index.md
Labels: priority.Medium, type.Documentation

#137 Add gui tests
  src/main/java/seedu/address/ui/CompletableDeadlineCard.java
  src/main/java/seedu/address/ui/CompletableTodoCard.java
  src/test/java/guitests/guihandles/CompletableDeadlineCardHandle.java
  src/test/java/guitests/guihandles/CompletableTodoCardHandle.java
  src/test/java/guitests/guihandles/EventCardHandle.java
  src/test/java/guitests/guihandles/ProjectCardHandle.java
  src/test/java/seedu/address/ui/CompletableDeadlineCardTest.java
  src/test/java/seedu/address/ui/CompletableTodoCardTest.java
  src/test/java/seedu/address/ui/EventCardTest.java
  src/test/java/seedu/address/ui/ProjectCardTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.Medium

#149 Dg UI command
  docs/DeveloperGuide.md
Labels: type.Documentation

#142 Add Today panel
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/ui/CompletableDeadlineCard.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/HomePanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SidePanel.java
  src/main/java/seedu/address/ui/TodayPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/HomePanel.css
  src/main/resources/view/HomePanel.fxml
  src/main/resources/view/SidePanel.fxml
  src/main/resources/view/TodayPanel.css
  src/main/resources/view/TodayPanel.fxml
  src/test/java/guitests/guihandles/TodayPanelHandle.java
  src/test/java/seedu/address/ui/TodayPanelTest.java
Labels: priority.High, type.Story

#156 Trial release v1.2.1
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#136 Add tests for Delete Todo command & it's related tests
  src/main/java/seedu/address/logic/parser/DeleteTodoCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteContactFromCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTodoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTodoCommandParserTest.java
Labels: priority.High, type.Story, type.Task

#153 Revamp projects view in UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ShowDeadlinesTabCommand.java
  src/main/java/seedu/address/logic/commands/ShowOverviewTabCommand.java
  src/main/java/seedu/address/logic/commands/ShowParticipantsTabCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/main/java/seedu/address/ui/UiCommand.java
  src/main/resources/view/CompletableDeadlineListCard.fxml
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ProjectDisplayPanel.css
  src/main/resources/view/ProjectDisplayPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/guitests/guihandles/ProjectDisplayPanelHandle.java
  src/test/java/seedu/address/logic/commands/ShowEventsTabCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowOverviewTabCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowParticipantsTabCommandTest.java
  src/test/java/seedu/address/ui/ProjectDisplayPanelTest.java
Labels: type.Enhancement

#161 Add Section on Task Model to DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#158 Update Developer Guide with design details
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#167 Add tests for DeleteDeadlineCommand & related classes
  src/main/java/seedu/address/logic/commands/DeleteDeadlineCommand.java
  src/main/java/seedu/address/logic/parser/DeleteDeadlineCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteDeadlineCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDeadlineCommandParserTest.java
Labels: priority.High, type.Story, type.Task

#170 Add tests for DeleteEventCommand & related classes
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
Labels: priority.High, type.Story, type.Task

#168 Bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/ListProjectsCommand.java
  src/main/java/seedu/address/logic/commands/MarkTodoCommand.java
  src/main/java/seedu/address/logic/commands/ViewProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/task/CompletableDeadline.java
  src/main/java/seedu/address/model/task/Repeatable.java
  src/main/java/seedu/address/model/task/deadline/Deadline.java
  src/main/java/seedu/address/model/task/repeatable/Event.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CompletableDeadlineListCard.fxml
  src/main/resources/view/CompletableTodoListCard.fxml
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/ProjectDisplayPanel.css
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/commands/ListProjectsCommandTest.java
Labels: type.Bug

#178 Update DG structure & introduction
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation, type.Task

#179 Update dg section on view projects feature
  docs/DeveloperGuide.md
  docs/diagrams/ViewProjectCommandSequenceDiagram.puml
  docs/images/ViewProjectCommandSequenceDiagram.png
Labels: type.Documentation

#180 Update styles for table of contents
  docs/_config.yml
  docs/_sass/minima/_layout.scss
Labels: type.Documentation

#181 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#183 Update UG About section
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation, type.Task

#184 Update UG
  docs/UserGuide.md
  docs/images/app_window_sections.png
Labels: type.Documentation

#187 Refactor duplicate todos/events/deadlines check
  src/main/java/seedu/address/logic/commands/AddDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/TodoList.java
  src/main/java/seedu/address/model/project/exceptions/DuplicateDeadlineException.java
  src/main/java/seedu/address/model/project/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/project/exceptions/DuplicateTodoException.java
Labels: type.Enhancement

#190 Implementation of updateP feature
  src/main/java/seedu/address/logic/commands/UpdateProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UpdateProjectCommandParser.java
Labels: priority.High, type.Story, type.Task

#191 Implementation of updateE feature
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventCommandParser.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
Labels: priority.High, type.Story, type.Task

#192 Implementation of updateT and updateD feature
  src/main/java/seedu/address/logic/commands/UpdateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTodoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateTodoCommandParser.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/TodoList.java
Labels: priority.High, type.Story, type.Task

#188 Show day
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/ui/CompletableDeadlineCard.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/TodayPanel.java
  src/test/java/seedu/address/ui/TodayPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.Enhancement

#186 Support multiple date formats
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateEventCommandParser.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, type.Enhancement

#198 Update yyyy in UG
  docs/UserGuide.md
Labels: priority.Low, type.Bug, type.Documentation

#204 Add command history feature
  src/main/java/seedu/address/logic/commandhistory/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/commandhistory/CommandHistoryTest.java
Labels: type.Enhancement

#210 Minor changes to UI
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/resources/view/CompletableDeadlineListCard.fxml
  src/main/resources/view/ProjectDisplayPanel.css
  src/main/resources/view/TodayPanel.css
Labels: type.Enhancement

#200 Add TimeUtil & Time field to Events
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/exceptions/TimeConversionException.java
  src/main/java/seedu/address/commons/util/TimeUtil.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/MarkEventCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateEventCommandParser.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/task/Repeatable.java
  src/main/java/seedu/address/model/task/repeatable/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventCard.fxml
  src/test/data/JsonColabFolderStorageTest/invalidAndValidContactColabFolder.json
  src/test/data/JsonColabFolderStorageTest/invalidAndValidProjectColabFolder.json
  src/test/data/JsonColabFolderStorageTest/invalidContactColabFolder.json
  src/test/data/JsonColabFolderStorageTest/invalidProjectColabFolder.json
  src/test/data/JsonSerializableColabFolderTest/duplicateContactColabFolder.json
  src/test/data/JsonSerializableColabFolderTest/duplicateProjectColabFolder.json
  src/test/data/JsonSerializableColabFolderTest/invalidContactColabFolder.json
  src/test/data/JsonSerializableColabFolderTest/invalidProjectColabFolder.json
  src/test/data/JsonSerializableColabFolderTest/typicalColabFolder.json
  src/test/java/guitests/guihandles/EventCardHandle.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/project/EventListTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/task/repeatable/EventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
  src/test/java/seedu/address/ui/EventCardTest.java
  src/test/java/seedu/address/ui/ProjectDisplayPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High, type.Enhancement, type.Story

#207 Create Help Panel
  src/main/java/seedu/address/logic/uicommands/ShowHelpUiCommand.java
  src/main/java/seedu/address/ui/CommandSyntax.java
  src/main/java/seedu/address/ui/HelpPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpPanel.css
  src/main/resources/view/HelpPanel.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/ProjectDisplayPanelHandle.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: type.Enhancement

#217 Update UG Structure & Details
  docs/UserGuide.md
Labels: priority.High, type.Documentation, type.Enhancement

#209 Implement undo redo feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ColabFolder.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/colabfolderhistory/ColabFolderHistory.java
  src/main/java/seedu/address/model/colabfolderhistory/SavedState.java
  src/main/java/seedu/address/model/colabfolderhistory/exceptions/NoRedoableStateException.java
  src/main/java/seedu/address/model/colabfolderhistory/exceptions/NoUndoableStateException.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/colabfolderhistory/ColabFolderHistoryTest.java
  src/test/java/seedu/address/model/colabfolderhistory/SavedStateTest.java
Labels: type.Story

#232 Fix sorted index bug
  src/main/java/seedu/address/logic/commands/DeleteDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeadlineCommand.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/test/java/seedu/address/logic/commands/DeleteDeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/model/project/DeadlineListTest.java
  src/test/java/seedu/address/model/project/EventListTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
Labels: priority.High, type.Bug

#230 Horizontal scroll UI
  src/main/java/seedu/address/ui/CompletableDeadlineCard.java
  src/main/java/seedu/address/ui/CompletableTodoCard.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/GroupmateCard.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/main/resources/view/CompletableDeadlineCard.fxml
  src/main/resources/view/CompletableTodoCard.fxml
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/GroupmateCard.fxml
  src/main/resources/view/ProjectDisplayPanel.css
  src/main/resources/view/TodayDeadlineCard.fxml
  src/main/resources/view/TodayEventCard.fxml
Labels: type.Enhancement

#235 Undo redo changes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewContactsCommand.java
  src/main/java/seedu/address/logic/commands/ViewOverviewCommand.java
  src/main/java/seedu/address/logic/commands/ViewProjectCommand.java
  src/main/java/seedu/address/logic/commands/ViewTodayCommand.java
  src/main/java/seedu/address/logic/commands/ViewTodosCommand.java
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement

#228 Ensure null values in json files are handled properly
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedGroupmate.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedTodo.java
  src/main/java/seedu/address/storage/JsonColabFolderStorage.java
  src/test/java/seedu/address/storage/JsonAdaptedDeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTodoTest.java
Labels: type.Task

#233 Update help window command syntax
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddTodoCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/ui/HelpPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/main/java/seedu/address/ui/ProjectListPanel.java
  src/main/java/seedu/address/ui/SidePanel.java
  src/main/resources/view/HelpPanel.css
  src/main/resources/view/HelpPanel.fxml
Labels: priority.High, type.Task

#240 Change all index to use i prefix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupmateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTodoCommand.java
  src/main/java/seedu/address/logic/commands/UpdateDeadlineCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventCommand.java
  src/main/java/seedu/address/logic/commands/UpdateGroupmateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTodoCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupmateCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTodoCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateGroupmateCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateTodoCommandParser.java
  src/main/java/seedu/address/ui/HelpPanel.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDeadlineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupmateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTodoCommandParserTest.java
Labels: type.Enhancement

#239 Add sorted feature to todos and groupmates
  src/main/java/seedu/address/logic/commands/DeleteTodoCommand.java
  src/main/java/seedu/address/logic/commands/MarkTodoCommand.java
  src/main/java/seedu/address/model/project/DeadlineList.java
  src/main/java/seedu/address/model/project/EventList.java
  src/main/java/seedu/address/model/project/GroupmateList.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/TodoList.java
  src/main/java/seedu/address/ui/ProjectDisplayPanel.java
  src/test/data/JsonSerializableColabFolderTest/typicalColabFolder.json
  src/test/java/seedu/address/logic/commands/DeleteGroupmateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTodoCommandTest.java
  src/test/java/seedu/address/model/project/GroupmateListTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/model/project/TodoListTest.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: type.Enhancement

#242 Updates UG with feature details.
  docs/UserGuide.md
Labels: priority.High, type.Documentation, type.Task

#247 Update User Guide on groupmate/contact related parts
  docs/UserGuide.md
Labels: type.Documentation

#249 Update ClearCommand to clear projects
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Enhancement, type.Story
